---  
- hosts: all  
  vars:  
    variable1: 'Hello'  
    variable2: 'My first playbook using template'  
  tasks:          
    - name: Basic Template Example  
      template:  
        src: example1.js
        dest: /config/output.txt